title: RodBlog rodblog
author: rodrigobscr
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The blog where RodZilla is King
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  rodrigobsc # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
