title: RodBlog rodblog
author: rodrigobscr
description: > # this means to ignore newlines until "baseurl:"
  The blog where RodZilla is King
# social links
github_username:  rodrigobsc # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# build settings
theme: jekyll-theme-minimal
